# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "logo:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
logo : /assets/images/paper-boat.svg

show_excerpts: false # set to true to show excerpts on the homepage

# Author settings
author: Name
email: your-email@domain.com
author_link: https://example.com
author_img: /assets/images/paper-boat.svg
about_author: Paper is a Jekyll theme for project documentation.

# Front Matter defaults
defaults:
  -
    scope:
      path: "docs/paper"
    values:
      layout: "doc"
      repo: "paper"
  -
    scope:
      path: "docs/minima"
    values:
      layout: "doc"
      repo: "minima"

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-paper

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jemoji
